# Generated by Django 5.2.13 on 2026-04-24 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='Plaka Numarası')),
                ('bus_type', models.CharField(choices=[('2+1', '2+1 VIP'), ('2+2', '2+2 Standart')], default='2+2', max_length=10, verbose_name='Otobüs Tipi')),
                ('capacity', models.PositiveIntegerField(default=40, verbose_name='Kapasite (Koltuk Sayısı)')),
            ],
            options={
                'verbose_name': 'Otobüs',
                'verbose_name_plural': 'Otobüsler',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Şehir Adı')),
            ],
            options={
                'verbose_name': 'Şehir',
                'verbose_name_plural': 'Şehirler',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(verbose_name='Kalkış Zamanı')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Bilet Fiyatı (TL)')),
                ('arrival_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='tickets.city', verbose_name='Varış Şehri')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.bus', verbose_name='Otobüs')),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='tickets.city', verbose_name='Kalkış Şehri')),
            ],
            options={
                'verbose_name': 'Sefer',
                'verbose_name_plural': 'Seferler',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField(verbose_name='Koltuk Numarası')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Satın Alma Tarihi')),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('iptal', 'İptal Edildi')], default='aktif', max_length=10, verbose_name='Durum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yolcu')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.trip', verbose_name='Sefer')),
            ],
            options={
                'verbose_name': 'Bilet',
                'verbose_name_plural': 'Biletler',
                'unique_together': {('trip', 'seat_number')},
            },
        ),
    ]
