# Generated by Django 5.2.13 on 2026-04-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='passenger_gender',
            field=models.CharField(choices=[('E', 'Erkek'), ('K', 'Kadın')], default='E', max_length=1, verbose_name='Yolcu Cinsiyeti'),
        ),
    ]
