# Generated by Django 5.2.13 on 2026-04-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_passenger_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='passenger_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Yolcu Adı Soyadı'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tc_no',
            field=models.CharField(max_length=11, null=True, verbose_name='TC Kimlik No'),
        ),
    ]
