# Generated by Django 5.2.13 on 2026-05-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_passenger_name_ticket_tc_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(choices=[('kart', 'Kredi / Banka Kartı'), ('nakit', 'Nakit (Terminalde Ödeme)')], default='kart', max_length=10, verbose_name='Ödeme Yöntemi'),
        ),
    ]
